modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/KleeSlabs/issues"

[[mods]]
modId="kleeslabs"
version="${file.jarVersion}"
displayName="KleeSlabs"
displayURL="https://mods.twelveiterations.com/mc/kleeslabs"
logoFile="kleeslabs-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Break only the half of a double slab that you're looking at.
'''

[[dependencies.kleeslabs]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.kleeslabs]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.kleeslabs]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
