modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/KleeSlabs/issues"

[[mods]]
modId="kleeslabs"
version="${file.jarVersion}"
displayName="KleeSlabs"
displayURL="https://blay09.net/mods/kleeslabs"
logoFile="kleeslabs-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Break only the half of a double slab that you're looking at.
'''

[[dependencies.kleeslabs]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.kleeslabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.kleeslabs]]
    modId="balm"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="NONE"
    side="BOTH"
